export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const SET_ALL_EMPLOYEES = "SET_ALL_EMPLOYEES";

export const LOGIN = "LOGIN";
export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";

export const GET_ALL_COMPUTERS = "GET_ALL_COMPUTERS";
export const SET_ALL_COMPUTERS = "SET_ALL_COMPUTERS";
export const CREATE_NEW_COMPUTER = "CREATE_NEW_COMPUTER";

export const CREATE_CLEAN_REQUEST = "CREATE_CLEAN_REQUEST";
export const SET_CLEAN_REQUESTS = "SET_CLEAN_REQUESTS";
export const GET_ALL_CLEAN_REQUESTS = "GET_ALL_CLEAN_REQUESTS";

export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
